#!/usr/bin/env node
/** Add tradeBonuses for expanded contraband lines across all countries. */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..', '..');
const countriesPath = path.join(root, 'backend', 'content', 'countries.json');
const countries = JSON.parse(fs.readFileSync(countriesPath, 'utf8'));

const newBonuses = {
  netherlands: {
    contraband_spices: 1.05,
    contraband_coffee: 0.95,
    contraband_fur_leather: 1.0,
    contraband_perfume: 1.15,
    contraband_counterfeit_cash: 1.1,
    contraband_rare_wine: 1.2,
    contraband_luxury_watches: 1.25,
    contraband_gold: 1.1,
  },
  belgium: {
    contraband_spices: 1.0,
    contraband_coffee: 1.05,
    contraband_fur_leather: 1.05,
    contraband_perfume: 1.1,
    contraband_counterfeit_cash: 1.05,
    contraband_rare_wine: 1.15,
    contraband_luxury_watches: 1.2,
    contraband_gold: 1.15,
  },
  germany: {
    contraband_spices: 1.1,
    contraband_coffee: 1.05,
    contraband_fur_leather: 1.05,
    contraband_perfume: 1.2,
    contraband_counterfeit_cash: 1.15,
    contraband_rare_wine: 1.25,
    contraband_luxury_watches: 0.85,
    contraband_gold: 1.2,
  },
  france: {
    contraband_spices: 1.15,
    contraband_coffee: 1.1,
    contraband_fur_leather: 1.2,
    contraband_perfume: 0.75,
    contraband_counterfeit_cash: 1.2,
    contraband_rare_wine: 0.7,
    contraband_luxury_watches: 1.15,
    contraband_gold: 1.25,
  },
  spain: {
    contraband_spices: 1.05,
    contraband_coffee: 1.0,
    contraband_fur_leather: 0.85,
    contraband_perfume: 1.1,
    contraband_counterfeit_cash: 1.1,
    contraband_rare_wine: 0.8,
    contraband_luxury_watches: 1.15,
    contraband_gold: 1.1,
  },
  italy: {
    contraband_spices: 1.1,
    contraband_coffee: 1.05,
    contraband_fur_leather: 1.15,
    contraband_perfume: 0.8,
    contraband_counterfeit_cash: 1.15,
    contraband_rare_wine: 0.75,
    contraband_luxury_watches: 1.1,
    contraband_gold: 1.2,
  },
  uk: {
    contraband_spices: 1.2,
    contraband_coffee: 1.15,
    contraband_fur_leather: 1.25,
    contraband_perfume: 0.9,
    contraband_counterfeit_cash: 1.25,
    contraband_rare_wine: 1.3,
    contraband_luxury_watches: 1.35,
    contraband_gold: 1.3,
  },
  switzerland: {
    contraband_spices: 1.15,
    contraband_coffee: 1.2,
    contraband_fur_leather: 1.2,
    contraband_perfume: 1.25,
    contraband_counterfeit_cash: 1.2,
    contraband_rare_wine: 1.35,
    contraband_luxury_watches: 0.75,
    contraband_gold: 0.8,
  },
  usa: {
    contraband_spices: 1.15,
    contraband_coffee: 1.1,
    contraband_fur_leather: 1.2,
    contraband_perfume: 1.25,
    contraband_counterfeit_cash: 1.3,
    contraband_rare_wine: 1.3,
    contraband_luxury_watches: 1.25,
    contraband_gold: 1.25,
  },
  mexico: {
    contraband_spices: 0.7,
    contraband_coffee: 0.85,
    contraband_fur_leather: 0.95,
    contraband_perfume: 0.95,
    contraband_counterfeit_cash: 0.75,
    contraband_rare_wine: 0.9,
    contraband_luxury_watches: 0.95,
    contraband_gold: 0.9,
  },
  colombia: {
    contraband_spices: 0.65,
    contraband_coffee: 0.6,
    contraband_fur_leather: 0.9,
    contraband_perfume: 0.9,
    contraband_counterfeit_cash: 0.7,
    contraband_rare_wine: 0.95,
    contraband_luxury_watches: 0.9,
    contraband_gold: 0.85,
  },
  brazil: {
    contraband_spices: 0.7,
    contraband_coffee: 0.65,
    contraband_fur_leather: 0.95,
    contraband_perfume: 1.0,
    contraband_counterfeit_cash: 0.85,
    contraband_rare_wine: 1.0,
    contraband_luxury_watches: 1.05,
    contraband_gold: 0.95,
  },
  argentina: {
    contraband_spices: 0.85,
    contraband_coffee: 0.8,
    contraband_fur_leather: 0.8,
    contraband_perfume: 1.05,
    contraband_counterfeit_cash: 0.9,
    contraband_rare_wine: 0.7,
    contraband_luxury_watches: 1.1,
    contraband_gold: 1.0,
  },
  japan: {
    contraband_spices: 1.2,
    contraband_coffee: 1.25,
    contraband_fur_leather: 1.3,
    contraband_perfume: 1.3,
    contraband_counterfeit_cash: 1.25,
    contraband_rare_wine: 1.35,
    contraband_luxury_watches: 0.85,
    contraband_gold: 1.35,
  },
  china: {
    contraband_spices: 1.0,
    contraband_coffee: 1.05,
    contraband_fur_leather: 1.05,
    contraband_perfume: 1.15,
    contraband_counterfeit_cash: 0.65,
    contraband_rare_wine: 1.2,
    contraband_luxury_watches: 1.2,
    contraband_gold: 1.15,
  },
  russia: {
    contraband_spices: 0.9,
    contraband_coffee: 0.95,
    contraband_fur_leather: 0.7,
    contraband_perfume: 1.1,
    contraband_counterfeit_cash: 0.75,
    contraband_rare_wine: 1.15,
    contraband_luxury_watches: 1.2,
    contraband_gold: 0.85,
  },
  turkey: {
    contraband_spices: 0.6,
    contraband_coffee: 0.7,
    contraband_fur_leather: 0.75,
    contraband_perfume: 1.0,
    contraband_counterfeit_cash: 0.95,
    contraband_rare_wine: 1.05,
    contraband_luxury_watches: 1.05,
    contraband_gold: 1.0,
  },
  united_arab_emirates: {
    contraband_spices: 1.1,
    contraband_coffee: 1.15,
    contraband_fur_leather: 1.25,
    contraband_perfume: 0.85,
    contraband_counterfeit_cash: 1.15,
    contraband_rare_wine: 1.4,
    contraband_luxury_watches: 0.8,
    contraband_gold: 0.75,
  },
  south_africa: {
    contraband_spices: 0.95,
    contraband_coffee: 0.9,
    contraband_fur_leather: 1.0,
    contraband_perfume: 1.1,
    contraband_counterfeit_cash: 1.0,
    contraband_rare_wine: 1.15,
    contraband_luxury_watches: 1.15,
    contraband_gold: 0.65,
  },
  australia: {
    contraband_spices: 1.25,
    contraband_coffee: 1.2,
    contraband_fur_leather: 1.3,
    contraband_perfume: 1.25,
    contraband_counterfeit_cash: 1.35,
    contraband_rare_wine: 1.35,
    contraband_luxury_watches: 1.4,
    contraband_gold: 1.35,
  },
};

for (const c of countries) {
  const extras = newBonuses[c.id];
  if (!extras) throw new Error(`missing bonuses for ${c.id}`);
  c.tradeBonuses = { ...c.tradeBonuses, ...extras };
}

fs.writeFileSync(countriesPath, JSON.stringify(countries, null, 2) + '\n');
console.log(`Updated ${countries.length} countries with 8 new trade bonus keys.`);
