CREATE TABLE IF NOT EXISTS crew_parts_storage_buildings (
  id INT NOT NULL AUTO_INCREMENT,
  crewId INT NOT NULL,
  style VARCHAR(32) NOT NULL DEFAULT 'camping',
  level INT NOT NULL DEFAULT 0,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_crew_parts_storage_crew (crewId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS crew_vehicle_parts_inventory (
  id INT NOT NULL AUTO_INCREMENT,
  crewId INT NOT NULL,
  carParts INT NOT NULL DEFAULT 0,
  motorcycleParts INT NOT NULL DEFAULT 0,
  boatParts INT NOT NULL DEFAULT 0,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_crew_vehicle_parts_crew (crewId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
