export type TerritoryAutoRegionSeed = {
  svg: string;
  name: string;
};

export const territoryAutoRegionSeeds: Record<string, TerritoryAutoRegionSeed[]> = {
  argentinaLow: [
    { svg: 'AR-T', name: 'Tucuman' },
    { svg: 'AR-V', name: 'Tierra del Fuego' },
    { svg: 'AR-D', name: 'San Luis' },
    { svg: 'AR-J', name: 'San Juan' },
    { svg: 'AR-S', name: 'Santa Fe' },
    { svg: 'AR-G', name: 'Santiago del Estero' },
    { svg: 'AR-Z', name: 'Santa Cruz' },
    { svg: 'AR-A', name: 'Salta' },
    { svg: 'AR-R', name: 'Rio Negro' },
    { svg: 'AR-Q', name: 'Neuquen' },
    { svg: 'AR-N', name: 'Misiones' },
    { svg: 'AR-M', name: 'Mendoza' },
    { svg: 'AR-F', name: 'La Rioja' },
    { svg: 'AR-L', name: 'La Pampa' },
    { svg: 'AR-Y', name: 'Jujuy' },
    { svg: 'AR-P', name: 'Formosa' },
    { svg: 'AR-E', name: 'Entre Rios' },
    { svg: 'AR-W', name: 'Corrientes' },
    { svg: 'AR-X', name: 'Cordoba' },
    { svg: 'AR-C', name: 'Ciudad de Buenos Aires' },
    { svg: 'AR-U', name: 'Chubut' },
    { svg: 'AR-H', name: 'Chaco' },
    { svg: 'AR-K', name: 'Catamarca' },
    { svg: 'AR-B', name: 'Buenos Aires' },
  ],
  australiaLow: [
    { svg: 'AU-NT', name: 'Northern Territory' },
    { svg: 'AU-WA', name: 'Western Australia' },
    { svg: 'AU-ACT', name: 'Australian Capital Territory' },
    { svg: 'AU-NSW', name: 'New South Wales' },
    { svg: 'AU-SA', name: 'South Australia' },
    { svg: 'AU-VIC', name: 'Victoria' },
    { svg: 'AU-QLD', name: 'Queensland' },
    { svg: 'AU-TAS', name: 'Tasmania' },
  ],
  belgium: [
    { svg: 'BE-VAN', name: 'Antwerpen' },
    { svg: 'BE-WBR', name: 'Walloon Brabant' },
    { svg: 'BE-BRU', name: 'Brussels Capital Region' },
    { svg: 'BE-WHT', name: 'Hainaut' },
    { svg: 'BE-WLG', name: 'Liege' },
    { svg: 'BE-VLI', name: 'Limburg' },
    { svg: 'BE-WLX', name: 'Luxembourg' },
    { svg: 'BE-VOV', name: 'East Flanders' },
    { svg: 'BE-WNA', name: 'Namur' },
    { svg: 'BE-VBR', name: 'Flemish Brabant' },
    { svg: 'BE-VWV', name: 'West Flanders' },
  ],
  brazilLow: [
    { svg: 'BR-AC', name: 'Acre' },
    { svg: 'BR-AL', name: 'Alagoas' },
    { svg: 'BR-AM', name: 'Amazonas' },
    { svg: 'BR-AP', name: 'Amapa' },
    { svg: 'BR-BA', name: 'Bahia' },
    { svg: 'BR-CE', name: 'Ceara' },
    { svg: 'BR-DF', name: 'Distrito Federal' },
    { svg: 'BR-ES', name: 'Espirito Santo' },
    { svg: 'BR-GO', name: 'Goias' },
    { svg: 'BR-MA', name: 'Maranhao' },
    { svg: 'BR-MG', name: 'Minas Gerais' },
    { svg: 'BR-MS', name: 'Mato Grosso do Sul' },
    { svg: 'BR-MT', name: 'Mato Grosso' },
    { svg: 'BR-PA', name: 'Para' },
    { svg: 'BR-PB', name: 'Paraiba' },
    { svg: 'BR-PE', name: 'Pernambuco' },
    { svg: 'BR-PI', name: 'Piaui' },
    { svg: 'BR-PR', name: 'Parana' },
    { svg: 'BR-RJ', name: 'Rio de Janeiro' },
    { svg: 'BR-RN', name: 'Rio Grande do Norte' },
    { svg: 'BR-RO', name: 'Rondonia' },
    { svg: 'BR-RR', name: 'Roraima' },
    { svg: 'BR-RS', name: 'Rio Grande do Sul' },
    { svg: 'BR-SC', name: 'Santa Catarina' },
    { svg: 'BR-SE', name: 'Sergipe' },
    { svg: 'BR-SP', name: 'Sao Paulo' },
    { svg: 'BR-TO', name: 'Tocantins' },
  ],
  chinaLow: [
    { svg: 'CN-AH', name: 'Anhui' },
    { svg: 'CN-BJ', name: 'Beijing' },
    { svg: 'CN-CQ', name: 'Chongqing' },
    { svg: 'CN-FJ', name: 'Fujian' },
    { svg: 'CN-GD', name: 'Guangdong' },
    { svg: 'CN-GS', name: 'Gansu' },
    { svg: 'CN-GX', name: 'Guangxi Zhuang' },
    { svg: 'CN-GZ', name: 'Guizhou' },
    { svg: 'CN-HA', name: 'Henan' },
    { svg: 'CN-HB', name: 'Hubei' },
    { svg: 'CN-HE', name: 'Hebei' },
    { svg: 'CN-HI', name: 'Hainan' },
    { svg: 'CN-HK', name: 'Hong Kong' },
    { svg: 'CN-HL', name: 'Heilongjiang' },
    { svg: 'CN-HN', name: 'Hunan' },
    { svg: 'CN-JL', name: 'Jilin' },
    { svg: 'CN-JS', name: 'Jiangsu' },
    { svg: 'CN-JX', name: 'Jiangxi' },
    { svg: 'CN-LN', name: 'Liaoning' },
    { svg: 'CN-MO', name: 'Macau' },
    { svg: 'CN-NM', name: 'Nei Mongol' },
    { svg: 'CN-NX', name: 'Ningxia Hui' },
    { svg: 'CN-QH', name: 'Qinghai' },
    { svg: 'CN-SC', name: 'Sichuan' },
    { svg: 'CN-SD', name: 'Shandong' },
    { svg: 'CN-SH', name: 'Shanghai' },
    { svg: 'CN-SN', name: 'Shaanxi' },
    { svg: 'CN-SX', name: 'Shanxi' },
    { svg: 'CN-TJ', name: 'Tianjin' },
    { svg: 'CN-TW', name: 'Taiwan' },
    { svg: 'CN-XJ', name: 'Xinjiang Uygur' },
    { svg: 'CN-XZ', name: 'Xizang Tibet' },
    { svg: 'CN-YN', name: 'Yunnan' },
    { svg: 'CN-ZJ', name: 'Zhejiang' },
  ],
  colombiaLow: [
    { svg: 'CO-VID', name: 'Vichada' },
    { svg: 'CO-VAU', name: 'Vaupes' },
    { svg: 'CO-VAC', name: 'Valle del Cauca' },
    { svg: 'CO-TOL', name: 'Tolima' },
    { svg: 'CO-SUC', name: 'Sucre' },
    { svg: 'CO-SAP', name: 'San Andres, Providencia y Santa Catalina' },
    { svg: 'CO-SAN', name: 'Santander' },
    { svg: 'CO-RIS', name: 'Risaralda' },
    { svg: 'CO-QUI', name: 'Quindio' },
    { svg: 'CO-PUT', name: 'Putumayo' },
    { svg: 'CO-NSA', name: 'Norte de Santander' },
    { svg: 'CO-NAR', name: 'Narino' },
    { svg: 'CO-MET', name: 'Meta' },
    { svg: 'CO-MAG', name: 'Magdalena' },
    { svg: 'CO-LAG', name: 'La Guajira' },
    { svg: 'CO-HUI', name: 'Huila' },
    { svg: 'CO-GUV', name: 'Guaviare' },
    { svg: 'CO-GUA', name: 'Guainia' },
    { svg: 'CO-DC', name: 'Distrito Capital de Bogota' },
    { svg: 'CO-CUN', name: 'Cundinamarca' },
    { svg: 'CO-COR', name: 'Cordoba' },
    { svg: 'CO-CHO', name: 'Choco' },
    { svg: 'CO-CES', name: 'Cesar' },
    { svg: 'CO-CAU', name: 'Cauca' },
    { svg: 'CO-CAS', name: 'Casanare' },
    { svg: 'CO-CAQ', name: 'Caqueta' },
    { svg: 'CO-CAL', name: 'Caldas' },
    { svg: 'CO-BOY', name: 'Boyaca' },
    { svg: 'CO-BOL', name: 'Bolivar' },
    { svg: 'CO-ATL', name: 'Atlantico' },
    { svg: 'CO-ARA', name: 'Arauca' },
    { svg: 'CO-ANT', name: 'Antioquia' },
    { svg: 'CO-AMA', name: 'Amazonas' },
  ],
  franceLow: [
    { svg: 'FR-PAC', name: 'Provence-Alpes-Cote d Azur' },
    { svg: 'FR-PDL', name: 'Pays de la Loire' },
    { svg: 'FR-OCC', name: 'Occitanie' },
    { svg: 'FR-NAQ', name: 'Nouvelle-Aquitaine' },
    { svg: 'FR-NOR', name: 'Normandie' },
    { svg: 'FR-IDF', name: 'Ile-de-France' },
    { svg: 'FR-HDF', name: 'Hauts-de-France' },
    { svg: 'FR-GES', name: 'Grand Est' },
    { svg: 'FR-COR', name: 'Corse' },
    { svg: 'FR-CVL', name: 'Centre-Val de Loire' },
    { svg: 'FR-BRE', name: 'Bretagne' },
    { svg: 'FR-BFC', name: 'Bourgogne-Franche-Comte' },
    { svg: 'FR-ARA', name: 'Auvergne-Rhone-Alpes' },
  ],
  germanyLow: [
    { svg: 'DE-BB', name: 'Brandenburg' },
    { svg: 'DE-BE', name: 'Berlin' },
    { svg: 'DE-BW', name: 'Baden-Wurttemberg' },
    { svg: 'DE-BY', name: 'Bavaria' },
    { svg: 'DE-HB', name: 'Bremen' },
    { svg: 'DE-HE', name: 'Hesse' },
    { svg: 'DE-HH', name: 'Hamburg' },
    { svg: 'DE-MV', name: 'Mecklenburg-Western Pomerania' },
    { svg: 'DE-NI', name: 'Lower Saxony' },
    { svg: 'DE-NW', name: 'North Rhine-Westphalia' },
    { svg: 'DE-RP', name: 'Rhineland-Palatinate' },
    { svg: 'DE-SH', name: 'Schleswig-Holstein' },
    { svg: 'DE-SL', name: 'Saarland' },
    { svg: 'DE-SN', name: 'Saxony' },
    { svg: 'DE-ST', name: 'Sachsen-Anhalt' },
    { svg: 'DE-TH', name: 'Thuringia' },
  ],
  italyLow: [
    { svg: 'FR-H', name: 'Corse' },
    { svg: 'MT', name: 'Malta' },
    { svg: 'SM', name: 'San Marino' },
    { svg: 'VA', name: 'Vatican City' },
    { svg: 'IT-21', name: 'Piemonte' },
    { svg: 'IT-23', name: 'Valle d Aosta' },
    { svg: 'IT-25', name: 'Lombardia' },
    { svg: 'IT-32', name: 'Trentino-Alto Adige' },
    { svg: 'IT-34', name: 'Veneto' },
    { svg: 'IT-36', name: 'Friuli-Venezia Giulia' },
    { svg: 'IT-42', name: 'Liguria' },
    { svg: 'IT-45', name: 'Emilia-Romagna' },
    { svg: 'IT-52', name: 'Toscana' },
    { svg: 'IT-55', name: 'Umbria' },
    { svg: 'IT-57', name: 'Marche' },
    { svg: 'IT-62', name: 'Lazio' },
    { svg: 'IT-65', name: 'Abruzzo' },
    { svg: 'IT-67', name: 'Molise' },
    { svg: 'IT-72', name: 'Campania' },
    { svg: 'IT-75', name: 'Puglia' },
    { svg: 'IT-77', name: 'Basilicata' },
    { svg: 'IT-78', name: 'Calabria' },
    { svg: 'IT-82', name: 'Sicilia' },
    { svg: 'IT-88', name: 'Sardegna' },
  ],
  japanLow: [
    { svg: 'JP-01', name: 'Hokkaido' },
    { svg: 'JP-02', name: 'Aomori' },
    { svg: 'JP-03', name: 'Iwate' },
    { svg: 'JP-04', name: 'Miyagi' },
    { svg: 'JP-05', name: 'Akita' },
    { svg: 'JP-06', name: 'Yamagata' },
    { svg: 'JP-07', name: 'Fukushima' },
    { svg: 'JP-08', name: 'Ibaraki' },
    { svg: 'JP-09', name: 'Tochigi' },
    { svg: 'JP-10', name: 'Gunma' },
    { svg: 'JP-12', name: 'Chiba' },
    { svg: 'JP-17', name: 'Ishikawa' },
    { svg: 'JP-18', name: 'Fukui' },
    { svg: 'JP-28', name: 'Hyogo' },
    { svg: 'JP-38', name: 'Ehime' },
    { svg: 'JP-40', name: 'Fukuoka' },
    { svg: 'JP-34', name: 'Hiroshima' },
    { svg: 'JP-37', name: 'Kagawa' },
    { svg: 'JP-14', name: 'Kanagawa' },
    { svg: 'JP-13', name: 'Tokyo' },
    { svg: 'JP-15', name: 'Niigata' },
    { svg: 'JP-16', name: 'Toyama' },
    { svg: 'JP-19', name: 'Yamanashi' },
    { svg: 'JP-11', name: 'Saitama' },
    { svg: 'JP-20', name: 'Nagano' },
    { svg: 'JP-21', name: 'Gifu' },
    { svg: 'JP-22', name: 'Shizuoka' },
    { svg: 'JP-23', name: 'Aichi' },
    { svg: 'JP-24', name: 'Mie' },
    { svg: 'JP-25', name: 'Shiga' },
    { svg: 'JP-26', name: 'Kyoto' },
    { svg: 'JP-27', name: 'Osaka' },
    { svg: 'JP-29', name: 'Nara' },
    { svg: 'JP-30', name: 'Wakayama' },
    { svg: 'JP-31', name: 'Tottori' },
    { svg: 'JP-32', name: 'Shimane' },
    { svg: 'JP-33', name: 'Okayama' },
    { svg: 'JP-35', name: 'Yamaguchi' },
    { svg: 'JP-36', name: 'Tokushima' },
    { svg: 'JP-39', name: 'Kochi' },
    { svg: 'JP-41', name: 'Saga' },
    { svg: 'JP-42', name: 'Nagasaki' },
    { svg: 'JP-43', name: 'Kumamoto' },
    { svg: 'JP-45', name: 'Miyazaki' },
    { svg: 'JP-44', name: 'Oita' },
    { svg: 'JP-46', name: 'Kagoshima' },
    { svg: 'JP-47', name: 'Okinawa' },
  ],
  mexicoLow: [
    { svg: 'MX-ZAC', name: 'Zacatecas' },
    { svg: 'MX-YUC', name: 'Yucatan' },
    { svg: 'MX-VER', name: 'Veracruz' },
    { svg: 'MX-TLA', name: 'Tlaxcala' },
    { svg: 'MX-TAM', name: 'Tamaulipas' },
    { svg: 'MX-TAB', name: 'Tabasco' },
    { svg: 'MX-SON', name: 'Sonora' },
    { svg: 'MX-SIN', name: 'Sinaloa' },
    { svg: 'MX-SLP', name: 'San Luis Potosi' },
    { svg: 'MX-ROO', name: 'Quintana Roo' },
    { svg: 'MX-QUE', name: 'Queretaro' },
    { svg: 'MX-PUE', name: 'Puebla' },
    { svg: 'MX-OAX', name: 'Oaxaca' },
    { svg: 'MX-NLE', name: 'Nuevo Leon' },
    { svg: 'MX-NAY', name: 'Nayarit' },
    { svg: 'MX-MOR', name: 'Morelos' },
    { svg: 'MX-MIC', name: 'Michoacan' },
    { svg: 'MX-MEX', name: 'Mexico' },
    { svg: 'MX-JAL', name: 'Jalisco' },
    { svg: 'MX-HID', name: 'Hidalgo' },
    { svg: 'MX-GRO', name: 'Guerrero' },
    { svg: 'MX-GUA', name: 'Guanajuato' },
    { svg: 'MX-DUR', name: 'Durango' },
    { svg: 'MX-CMX', name: 'Ciudad de Mexico' },
    { svg: 'MX-COL', name: 'Colima' },
    { svg: 'MX-COA', name: 'Coahuila' },
    { svg: 'MX-CHH', name: 'Chihuahua' },
    { svg: 'MX-CHP', name: 'Chiapas' },
    { svg: 'MX-CAM', name: 'Campeche' },
    { svg: 'MX-BCS', name: 'Baja California Sur' },
    { svg: 'MX-BCN', name: 'Baja California' },
    { svg: 'MX-AGU', name: 'Aguascalientes' },
  ],
  russiaLow: [
    { svg: 'RU-ZAB', name: 'Zabaykalsky' },
    { svg: 'RU-YEV', name: 'Yevrey' },
    { svg: 'RU-YAR', name: 'Yaroslavl' },
    { svg: 'RU-YAN', name: 'Yamalo-Nenets' },
    { svg: 'RU-VOR', name: 'Voronezh' },
    { svg: 'RU-VLG', name: 'Vologda' },
    { svg: 'RU-VGG', name: 'Volgograd' },
    { svg: 'RU-VLA', name: 'Vladimir' },
    { svg: 'RU-ULY', name: 'Ulyanovsk' },
    { svg: 'RU-UD', name: 'Udmurt' },
    { svg: 'RU-TYU', name: 'Tyumen' },
    { svg: 'RU-TVE', name: 'Tver' },
    { svg: 'RU-TY', name: 'Tuva' },
    { svg: 'RU-TUL', name: 'Tula' },
    { svg: 'RU-TOM', name: 'Tomsk' },
    { svg: 'RU-TA', name: 'Tatarstan' },
    { svg: 'RU-TAM', name: 'Tambov' },
    { svg: 'RU-SVE', name: 'Sverdlovsk' },
    { svg: 'RU-STA', name: 'Stavropol' },
    { svg: 'RU-SMO', name: 'Smolensk' },
    { svg: 'RU-SAR', name: 'Saratov' },
    { svg: 'RU-SAM', name: 'Samara' },
    { svg: 'RU-SAK', name: 'Sakhalin' },
    { svg: 'RU-SA', name: 'Sakha' },
    { svg: 'RU-RYA', name: 'Ryazan' },
    { svg: 'RU-ROS', name: 'Rostov' },
    { svg: 'RU-PSK', name: 'Pskov' },
    { svg: 'RU-PRI', name: 'Primorsky' },
    { svg: 'RU-PER', name: 'Perm' },
    { svg: 'RU-PNZ', name: 'Penza' },
    { svg: 'RU-ORE', name: 'Orenburg' },
    { svg: 'RU-ORL', name: 'Oryol' },
    { svg: 'RU-OMS', name: 'Omsk' },
    { svg: 'RU-NVS', name: 'Novosibirsk' },
    { svg: 'RU-NGR', name: 'Novgorod' },
    { svg: 'RU-SE', name: 'North Ossetia-Alania' },
    { svg: 'RU-NIZ', name: 'Nizhegorod' },
    { svg: 'RU-NEN', name: 'Nenets' },
    { svg: 'RU-MUR', name: 'Murmansk' },
    { svg: 'RU-MOS', name: 'Moskva' },
    { svg: 'RU-MOW', name: 'Moscow City' },
    { svg: 'RU-MO', name: 'Mordovia' },
    { svg: 'RU-ME', name: 'Mariy-El' },
    { svg: 'RU-MAG', name: 'Magadan' },
    { svg: 'RU-LIP', name: 'Lipetsk' },
    { svg: 'RU-LEN', name: 'Leningrad' },
    { svg: 'RU-KRS', name: 'Kursk' },
    { svg: 'RU-KGN', name: 'Kurgan' },
    { svg: 'RU-KYA', name: 'Krasnoyarsk' },
    { svg: 'RU-KDA', name: 'Krasnodar' },
    { svg: 'RU-KOS', name: 'Kostroma' },
    { svg: 'RU-KO', name: 'Komi' },
    { svg: 'RU-KIR', name: 'Kirov' },
    { svg: 'RU-KHM', name: 'Khanty-Mansiysk' },
    { svg: 'RU-KK', name: 'Khakassia' },
    { svg: 'RU-KHA', name: 'Khabarovsk' },
    { svg: 'RU-KEM', name: 'Kemerovo' },
    { svg: 'RU-KR', name: 'Karelia' },
    { svg: 'RU-KC', name: 'Karachay-Cherkess' },
    { svg: 'RU-KAM', name: 'Kamchatka' },
    { svg: 'RU-KLU', name: 'Kaluga' },
    { svg: 'RU-KL', name: 'Kalmykia' },
    { svg: 'RU-KGD', name: 'Kaliningrad' },
    { svg: 'RU-KB', name: 'Kabardino-Balkar' },
    { svg: 'RU-IVA', name: 'Ivanovo' },
    { svg: 'RU-IRK', name: 'Irkutsk' },
    { svg: 'RU-IN', name: 'Ingushetia' },
    { svg: 'RU-AL', name: 'Altay' },
    { svg: 'RU-DA', name: 'Dagestan' },
    { svg: 'RU-SPE', name: 'St Petersburg' },
    { svg: 'RU-CU', name: 'Chuvash' },
    { svg: 'RU-CHU', name: 'Chukotka' },
    { svg: 'RU-CHE', name: 'Chelyabinsk' },
    { svg: 'RU-CE', name: 'Chechnya' },
    { svg: 'RU-BU', name: 'Buryatiya' },
    { svg: 'RU-BRY', name: 'Bryansk' },
    { svg: 'RU-BEL', name: 'Belgorod' },
    { svg: 'RU-BA', name: 'Bashkortostan' },
    { svg: 'RU-AST', name: 'Astrakhan' },
    { svg: 'RU-ARK', name: 'Arkhangelsk' },
    { svg: 'RU-AMU', name: 'Amur' },
    { svg: 'RU-ALT', name: 'Altay Kray' },
    { svg: 'RU-AD', name: 'Adygeya' },
  ],
  southAfricaLow: [
    { svg: 'ZA-WC', name: 'Western Cape' },
    { svg: 'ZA-NW', name: 'North West' },
    { svg: 'ZA-KZN', name: 'KwaZulu-Natal' },
    { svg: 'ZA-NC', name: 'Northern Cape' },
    { svg: 'ZA-MP', name: 'Mpumalanga' },
    { svg: 'ZA-LP', name: 'Limpopo' },
    { svg: 'ZA-GP', name: 'Gauteng' },
    { svg: 'ZA-FS', name: 'Free State' },
    { svg: 'ZA-EC', name: 'Eastern Cape' },
    { svg: 'LS', name: 'Lesotho' },
  ],
  spainLow: [
    { svg: 'ES-VC', name: 'Valencia' },
    { svg: 'ES-PV', name: 'Pais Vasco' },
    { svg: 'ES-IB', name: 'Islas Baleares' },
    { svg: 'ES-NC', name: 'Navarra' },
    { svg: 'ES-MC', name: 'Murcia' },
    { svg: 'ES-MD', name: 'Madrid' },
    { svg: 'ES-RI', name: 'La Rioja' },
    { svg: 'ES-GA', name: 'Galicia' },
    { svg: 'ES-EX', name: 'Extremadura' },
    { svg: 'ES-CT', name: 'Cataluna' },
    { svg: 'ES-CN', name: 'Islas Canarias' },
    { svg: 'ES-CM', name: 'Castilla-La Mancha' },
    { svg: 'ES-CL', name: 'Castilla y Leon' },
    { svg: 'ES-CB', name: 'Cantabria' },
    { svg: 'ES-AS', name: 'Asturias' },
    { svg: 'ES-AR', name: 'Aragon' },
    { svg: 'ES-AN', name: 'Andalucia' },
  ],
  switzerlandLow: [
    { svg: 'CH-AG', name: 'Aargau' },
    { svg: 'CH-AI', name: 'Appenzell Inner-Rhoden' },
    { svg: 'CH-AR', name: 'Appenzell Ausser-Rhoden' },
    { svg: 'CH-BL', name: 'Basel-Landschaft' },
    { svg: 'CH-BE', name: 'Bern' },
    { svg: 'CH-BS', name: 'Basel-Stadt' },
    { svg: 'CH-FR', name: 'Fribourg' },
    { svg: 'CH-GE', name: 'Geneve' },
    { svg: 'CH-GL', name: 'Glarus' },
    { svg: 'CH-GR', name: 'Graubunden' },
    { svg: 'CH-JU', name: 'Jura' },
    { svg: 'CH-LU', name: 'Luzern' },
    { svg: 'CH-NE', name: 'Neuchatel' },
    { svg: 'CH-NW', name: 'Nidwalden' },
    { svg: 'CH-OW', name: 'Obwalden' },
    { svg: 'CH-SG', name: 'Sankt Gallen' },
    { svg: 'CH-SH', name: 'Schaffhausen' },
    { svg: 'CH-SO', name: 'Solothurn' },
    { svg: 'CH-SZ', name: 'Schwyz' },
    { svg: 'CH-TG', name: 'Thurgau' },
    { svg: 'CH-TI', name: 'Ticino' },
    { svg: 'CH-UR', name: 'Uri' },
    { svg: 'CH-VD', name: 'Vaud' },
    { svg: 'CH-VS', name: 'Valais' },
    { svg: 'CH-ZG', name: 'Zug' },
    { svg: 'CH-ZH', name: 'Zurich' },
    { svg: 'IT-CO', name: 'Campione d Italia' },
  ],
  turkeyLow: [
    { svg: 'TR-01', name: 'Adana' },
    { svg: 'TR-02', name: 'Adiyaman' },
    { svg: 'TR-03', name: 'Afyon' },
    { svg: 'TR-04', name: 'Agri' },
    { svg: 'TR-68', name: 'Aksaray' },
    { svg: 'TR-05', name: 'Amasya' },
    { svg: 'TR-06', name: 'Ankara' },
    { svg: 'TR-07', name: 'Antalya' },
    { svg: 'TR-75', name: 'Ardahan' },
    { svg: 'TR-08', name: 'Artvin' },
    { svg: 'TR-09', name: 'Aydin' },
    { svg: 'TR-10', name: 'Balikesir' },
    { svg: 'TR-74', name: 'Bartin' },
    { svg: 'TR-72', name: 'Batman' },
    { svg: 'TR-69', name: 'Bayburt' },
    { svg: 'TR-11', name: 'Bilecik' },
    { svg: 'TR-12', name: 'Bingol' },
    { svg: 'TR-13', name: 'Bitlis' },
    { svg: 'TR-14', name: 'Bolu' },
    { svg: 'TR-15', name: 'Burdur' },
    { svg: 'TR-16', name: 'Bursa' },
    { svg: 'TR-17', name: 'Canakkale' },
    { svg: 'TR-18', name: 'Cankiri' },
    { svg: 'TR-19', name: 'Corum' },
    { svg: 'TR-20', name: 'Denizli' },
    { svg: 'TR-21', name: 'Diyarbakir' },
    { svg: 'TR-81', name: 'Duzce' },
    { svg: 'TR-22', name: 'Edirne' },
    { svg: 'TR-23', name: 'Elazig' },
    { svg: 'TR-24', name: 'Erzincan' },
    { svg: 'TR-25', name: 'Erzurum' },
    { svg: 'TR-26', name: 'Eskisehir' },
    { svg: 'TR-27', name: 'Gaziantep' },
    { svg: 'TR-28', name: 'Giresun' },
    { svg: 'TR-29', name: 'Gumushane' },
    { svg: 'TR-30', name: 'Hakkari' },
    { svg: 'TR-31', name: 'Hatay' },
    { svg: 'TR-33', name: 'Mersin' },
    { svg: 'TR-76', name: 'Igdir' },
    { svg: 'TR-32', name: 'Isparta' },
    { svg: 'TR-34', name: 'Istanbul' },
    { svg: 'TR-35', name: 'Izmir' },
    { svg: 'TR-46', name: 'Kahramanmaras' },
    { svg: 'TR-78', name: 'Karabuk' },
    { svg: 'TR-70', name: 'Karaman' },
    { svg: 'TR-36', name: 'Kars' },
    { svg: 'TR-37', name: 'Kastamonu' },
    { svg: 'TR-38', name: 'Kayseri' },
    { svg: 'TR-79', name: 'Kilis' },
    { svg: 'TR-71', name: 'Kirikkale' },
    { svg: 'TR-39', name: 'Kirklareli' },
    { svg: 'TR-40', name: 'Kirsehir' },
    { svg: 'TR-41', name: 'Kocaeli' },
    { svg: 'TR-42', name: 'Konya' },
    { svg: 'TR-43', name: 'Kutahya' },
    { svg: 'TR-44', name: 'Malatya' },
    { svg: 'TR-45', name: 'Manisa' },
    { svg: 'TR-47', name: 'Mardin' },
    { svg: 'TR-48', name: 'Mugla' },
    { svg: 'TR-49', name: 'Mus' },
    { svg: 'TR-50', name: 'Nevsehir' },
    { svg: 'TR-51', name: 'Nigde' },
    { svg: 'TR-52', name: 'Ordu' },
    { svg: 'TR-80', name: 'Osmaniye' },
    { svg: 'TR-53', name: 'Rize' },
    { svg: 'TR-54', name: 'Sakarya' },
    { svg: 'TR-55', name: 'Samsun' },
    { svg: 'TR-63', name: 'Sanliurfa' },
    { svg: 'TR-56', name: 'Siirt' },
    { svg: 'TR-57', name: 'Sinop' },
    { svg: 'TR-73', name: 'Sirnak' },
    { svg: 'TR-58', name: 'Sivas' },
    { svg: 'TR-59', name: 'Tekirdag' },
    { svg: 'TR-60', name: 'Tokat' },
    { svg: 'TR-61', name: 'Trabzon' },
    { svg: 'TR-62', name: 'Tunceli' },
    { svg: 'TR-64', name: 'Usak' },
    { svg: 'TR-65', name: 'Van' },
    { svg: 'TR-77', name: 'Yalova' },
    { svg: 'TR-66', name: 'Yozgat' },
    { svg: 'TR-67', name: 'Zonguldak' },
  ],
  ukLow: [
    { svg: 'GB-SCT', name: 'Scotland' },
    { svg: 'GB-UKC', name: 'North East England' },
    { svg: 'GB-UKD', name: 'North West England' },
    { svg: 'GB-UKE', name: 'Yorkshire and the Humber' },
    { svg: 'GB-UKF', name: 'East Midlands' },
    { svg: 'GB-UKG', name: 'West Midlands' },
    { svg: 'GB-UKH', name: 'East of England' },
    { svg: 'GB-UKI', name: 'Greater London' },
    { svg: 'GB-UKJ', name: 'South East England' },
    { svg: 'GB-UKK', name: 'South West England' },
    { svg: 'GB-WLS', name: 'Wales' },
    { svg: 'GB-NIR', name: 'Northern Ireland' },
    { svg: 'GG', name: 'Guernsey' },
    { svg: 'JE', name: 'Jersey' },
    { svg: 'IM', name: 'Isle of Man' },
    { svg: 'IE', name: 'Ireland' },
  ],
  usaLow: [
    { svg: 'US-AK', name: 'Alaska' },
    { svg: 'US-AL', name: 'Alabama' },
    { svg: 'US-AR', name: 'Arkansas' },
    { svg: 'US-AZ', name: 'Arizona' },
    { svg: 'US-CA', name: 'California' },
    { svg: 'US-CO', name: 'Colorado' },
    { svg: 'US-CT', name: 'Connecticut' },
    { svg: 'US-DC', name: 'District of Columbia' },
    { svg: 'US-DE', name: 'Delaware' },
    { svg: 'US-FL', name: 'Florida' },
    { svg: 'US-GA', name: 'Georgia' },
    { svg: 'US-HI', name: 'Hawaii' },
    { svg: 'US-IA', name: 'Iowa' },
    { svg: 'US-ID', name: 'Idaho' },
    { svg: 'US-IL', name: 'Illinois' },
    { svg: 'US-IN', name: 'Indiana' },
    { svg: 'US-KS', name: 'Kansas' },
    { svg: 'US-KY', name: 'Kentucky' },
    { svg: 'US-LA', name: 'Louisiana' },
    { svg: 'US-MA', name: 'Massachusetts' },
    { svg: 'US-MD', name: 'Maryland' },
    { svg: 'US-ME', name: 'Maine' },
    { svg: 'US-MI', name: 'Michigan' },
    { svg: 'US-MN', name: 'Minnesota' },
    { svg: 'US-MO', name: 'Missouri' },
    { svg: 'US-MS', name: 'Mississippi' },
    { svg: 'US-MT', name: 'Montana' },
    { svg: 'US-NC', name: 'North Carolina' },
    { svg: 'US-ND', name: 'North Dakota' },
    { svg: 'US-NE', name: 'Nebraska' },
    { svg: 'US-NH', name: 'New Hampshire' },
    { svg: 'US-NJ', name: 'New Jersey' },
    { svg: 'US-NM', name: 'New Mexico' },
    { svg: 'US-NV', name: 'Nevada' },
    { svg: 'US-NY', name: 'New York' },
    { svg: 'US-OH', name: 'Ohio' },
    { svg: 'US-OK', name: 'Oklahoma' },
    { svg: 'US-OR', name: 'Oregon' },
    { svg: 'US-PA', name: 'Pennsylvania' },
    { svg: 'US-RI', name: 'Rhode Island' },
    { svg: 'US-SC', name: 'South Carolina' },
    { svg: 'US-SD', name: 'South Dakota' },
    { svg: 'US-TN', name: 'Tennessee' },
    { svg: 'US-TX', name: 'Texas' },
    { svg: 'US-UT', name: 'Utah' },
    { svg: 'US-VA', name: 'Virginia' },
    { svg: 'US-VT', name: 'Vermont' },
    { svg: 'US-WA', name: 'Washington' },
    { svg: 'US-WI', name: 'Wisconsin' },
    { svg: 'US-WV', name: 'West Virginia' },
    { svg: 'US-WY', name: 'Wyoming' },
  ],
};
