INSERT INTO `runtime_config` (`configKey`, `configValue`)
VALUES
  ('DRUG_WHOLESALE_MIN_GRAMS', '250'),
  ('DRUG_WHOLESALE_SPREAD_BPS', '1500'),
  ('DRUG_WHOLESALE_VOLUME_BONUS_BPS_PER_KG', '200'),
  ('DRUG_WHOLESALE_VOLUME_BONUS_CAP_BPS', '600'),
  ('DRUG_WHOLESALE_SCARCITY_WINDOW_H', '24'),
  ('DRUG_WHOLESALE_SCARCITY_CAP_BPS', '1000'),
  ('DRUG_WHOLESALE_FBI_HEAT_PER_KG', '2'),
  ('DRUG_WHOLESALE_DRUG_HEAT', '4'),
  ('COUNTRY_POLICE_GAIN_DRUG_WHOLESALE', '1')
ON DUPLICATE KEY UPDATE `configKey` = `configKey`;
