#!/usr/bin/env node
/**
 * Reads scripts/_help_topics_extracted.json (from extract_help_topics_to_json.mjs),
 * merges helpTopic* strings into app_en.arb + app_nl.arb, regenerates
 * client/lib/data/help_content.dart and client/lib/l10n/help_topic_localizations.dart.
 *
 * Then: merge_arb_missing_from_en for other locales, translate_arb_english_fallback --prefix=helpTopic,
 * flutter gen-l10n, verify_arb_parity.
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');
const extractPath = path.join(__dirname, '_help_topics_extracted.json');
const l10nDir = path.join(root, 'client', 'lib', 'l10n');
const dataDir = path.join(root, 'client', 'lib', 'data');

function idToPascal(id) {
  return id
    .split('-')
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('');
}

function buildSwitch(rows, getterForPascal) {
  const lines = rows.map((r) => {
    const p = idToPascal(r.id);
    return `    '${r.id}' => ${getterForPascal(p)},`;
  });
  return `switch (topicId) {\n${lines.join('\n')}\n    _ => '',\n  }`;
}

const rows = JSON.parse(fs.readFileSync(extractPath, 'utf8'));

function applyArb(filePath, lang) {
  const arb = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  for (const row of rows) {
    const p = idToPascal(row.id);
    const base = `helpTopic${p}`;
    if (lang === 'en') {
      arb[`${base}Category`] = row.categoryEn;
      arb[`${base}Title`] = row.titleEn;
      arb[`${base}Summary`] = row.summaryEn;
      arb[`${base}How`] = row.howEn.join('\n');
      arb[`${base}Tips`] = row.tipsEn.join('\n');
    } else {
      arb[`${base}Category`] = row.categoryNl;
      arb[`${base}Title`] = row.titleNl;
      arb[`${base}Summary`] = row.summaryNl;
      arb[`${base}How`] = row.howNl.join('\n');
      arb[`${base}Tips`] = row.tipsNl.join('\n');
    }
  }
  fs.writeFileSync(filePath, `${JSON.stringify(arb, null, 2)}\n`, 'utf8');
}

applyArb(path.join(l10nDir, 'app_en.arb'), 'en');
applyArb(path.join(l10nDir, 'app_nl.arb'), 'nl');

const helpLines = rows.map((r) => {
  const pp = r.protocolPath.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
  return `  HelpTopic(
    id: '${r.id}',
    icon: ${r.icon},
    protocolPath: '${pp}',
  ),`;
});

const helpContent = `import 'package:flutter/material.dart';

class HelpTopic {
  const HelpTopic({
    required this.id,
    required this.icon,
    required this.protocolPath,
  });

  final String id;
  final IconData icon;
  final String protocolPath;
}

const List<HelpTopic> helpTopics = [
${helpLines.join('\n')}
];
`;

fs.writeFileSync(path.join(dataDir, 'help_content.dart'), helpContent, 'utf8');

const swCat = buildSwitch(rows, (p) => `helpTopic${p}Category`);
const swTitle = buildSwitch(rows, (p) => `helpTopic${p}Title`);
const swSum = buildSwitch(rows, (p) => `helpTopic${p}Summary`);
const swHow = buildSwitch(rows, (p) => `helpTopic${p}How`);
const swTips = buildSwitch(rows, (p) => `helpTopic${p}Tips`);

const l10nDart = `// GENERATED by scripts/apply_help_topics_l10n.mjs — re-run after changing help topics.
import 'app_localizations.dart';

extension HelpTopicLocalizations on AppLocalizations {
  String helpTopicCategoryStr(String topicId) => ${swCat};

  String helpTopicTitleStr(String topicId) => ${swTitle};

  String helpTopicSummaryStr(String topicId) => ${swSum};

  String helpTopicHowStr(String topicId) => ${swHow};

  String helpTopicTipsStr(String topicId) => ${swTips};

  List<String> helpTopicHowBullets(String topicId) =>
      helpTopicHowStr(topicId).split('\\n').where((s) => s.isNotEmpty).toList();

  List<String> helpTopicTipsBullets(String topicId) =>
      helpTopicTipsStr(topicId).split('\\n').where((s) => s.isNotEmpty).toList();

  String helpTopicSearchLower(String topicId) {
    final buf = StringBuffer()
      ..write(helpTopicTitleStr(topicId))
      ..write(' ')
      ..write(helpTopicSummaryStr(topicId))
      ..write(' ')
      ..write(helpTopicCategoryStr(topicId))
      ..write(' ')
      ..write(helpTopicHowStr(topicId))
      ..write(' ')
      ..write(helpTopicTipsStr(topicId));
    return buf.toString().toLowerCase();
  }
}
`;

fs.writeFileSync(
  path.join(l10nDir, 'help_topic_localizations.dart'),
  l10nDart,
  'utf8',
);

console.log(
  `apply_help_topics_l10n: ${rows.length} topics → ARB (en+nl), help_content.dart, help_topic_localizations.dart`,
);
