#!/usr/bin/env node
/**
 * Generates admin/src/i18n/translations.ts and inlineMessages.ts from App.tsx (nl+en)
 * using google-translate-api-x (EN -> de, fr, es, it, pl, pt). Uses a cache file for reruns.
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { translate } from 'google-translate-api-x';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');
const appTsx = path.join(root, 'admin/src/App.tsx');
const cachePath = path.join(__dirname, '.translate_cache.json');
const OUT_DIR = path.join(root, 'admin/src/i18n');

const TARGETS = ['de', 'fr', 'es', 'it', 'pl', 'pt'];
const DELAY_MS = 150;

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

function loadCache() {
  try {
    return JSON.parse(fs.readFileSync(cachePath, 'utf8'));
  } catch {
    return {};
  }
}

function saveCache(c) {
  fs.writeFileSync(cachePath, JSON.stringify(c, null, 2), 'utf8');
}

let cache = loadCache();

function cacheKey(from, to, text) {
  return `${from}|${to}|${text}`;
}

async function trText(text, to) {
  const k = cacheKey('en', to, text);
  if (cache[k]) return cache[k];
  let lastErr;
  for (let attempt = 0; attempt < 8; attempt++) {
    try {
      await sleep(DELAY_MS + attempt * 120);
      const r = await translate(text, {
        from: 'en',
        to,
        forceBatch: false,
        rejectOnPartialFail: false,
      });
      const out = r.text ?? text;
      cache[k] = out;
      return out;
    } catch (e) {
      lastErr = e;
      if (attempt === 7) break;
    }
  }
  throw lastErr;
}

function extractTranslationsObject() {
  const txt = fs.readFileSync(appTsx, 'utf8');
  const m = txt.match(/const translations = (\{[\s\S]*\n\}) as const/);
  if (!m) throw new Error('Could not parse translations from App.tsx');
  // eslint-disable-next-line no-eval
  return (0, eval)('(' + m[1] + ')');
}

function extractInlinePairs() {
  const txt = fs.readFileSync(appTsx, 'utf8');
  /** Multiline-safe: l( then optional ws, "...", ",", "..." ) */
  const re =
    /\bl\(\s*"((?:[^"\\]|\\.)*)"\s*,\s*"((?:[^"\\]|\\.)*)"\s*\)/gs;
  let m;
  const seen = new Set();
  const pairs = [];
  const unescape = (s) => {
    try {
      return JSON.parse('"' + s + '"');
    } catch {
      return JSON.parse('"' + s.replace(/\\/g, '\\\\') + '"');
    }
  };
  while ((m = re.exec(txt))) {
    const nl = unescape(m[1]);
    const en = unescape(m[2]);
    const k = nl + '\0' + en;
    if (seen.has(k)) continue;
    seen.add(k);
    pairs.push({ nl, en });
  }
  return pairs;
}

async function main() {
  const base = extractTranslationsObject();
  const en = base.en;
  const nl = base.nl;

  const keys = Object.keys(en);
  if (keys.length !== Object.keys(nl).length) {
    throw new Error('nl/en key count mismatch');
  }

  const out = { nl: { ...nl }, en: { ...en } };
  for (const lang of TARGETS) {
    out[lang] = {};
    let i = 0;
    for (const key of keys) {
      const src = en[key];
      process.stdout.write(`\r[translations ${lang}] ${i + 1}/${keys.length}   `);
      out[lang][key] = await trText(src, lang);
      i++;
      if (i % 20 === 0) saveCache(cache);
    }
    process.stdout.write('\n');
  }

  const inlinePairs = extractInlinePairs();
  const rows = {};
  let j = 0;
  for (const { nl: n, en: e } of inlinePairs) {
    const k = n + '\0' + e;
    process.stdout.write(`\r[inline] ${j + 1}/${inlinePairs.length}   `);
    rows[k] = { nl: n, en: e };
    for (const lang of TARGETS) {
      rows[k][lang] = await trText(e, lang);
    }
    j++;
    if (j % 10 === 0) saveCache(cache);
  }
  process.stdout.write('\n');
  saveCache(cache);

  if (!fs.existsSync(OUT_DIR)) fs.mkdirSync(OUT_DIR, { recursive: true });

  const tsTranslations = `/* eslint-disable */
/* Auto-generated by scripts/build_admin_i18n.mjs — do not edit by hand; re-run the script. */
export const translations = ${JSON.stringify(out, null, 2)} as const;
export type AdminLanguage = keyof typeof translations;
`;

  const tsInlineFixed = `/* eslint-disable */
/* Auto-generated by scripts/build_admin_i18n.mjs */
import type { AdminLanguage } from './translations';

const SEP = String.fromCharCode(0);

export const ADMIN_INLINE_ROWS: Record<string, { nl: string; en: string; de: string; fr: string; es: string; it: string; pl: string; pt: string }> = ${JSON.stringify(rows, null, 2)};

export function getAdminTr(
  lang: AdminLanguage,
  nl: string,
  en: string,
): string {
  if (lang === 'nl') return nl;
  if (lang === 'en') return en;
  const row = ADMIN_INLINE_ROWS[nl + SEP + en];
  if (row) {
    const s = (row as Record<string, string>)[lang as string];
    if (s) return s;
  }
  return en;
}
`;

  fs.writeFileSync(path.join(OUT_DIR, 'translations.ts'), tsTranslations, 'utf8');
  fs.writeFileSync(path.join(OUT_DIR, 'inlineMessages.ts'), tsInlineFixed, 'utf8');
  console.log('Wrote', path.join(OUT_DIR, 'translations.ts'));
  console.log('Wrote', path.join(OUT_DIR, 'inlineMessages.ts'));
  console.log('Cache entries:', Object.keys(cache).length);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
