// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXjRbRe0g1mpyGcXaFHT-291dI7TfAZao',
    appId: '1:572351438540:web:fa4cd2b00faf9602800c69',
    messagingSenderId: '572351438540',
    projectId: 'the-mob-state',
    authDomain: 'the-mob-state.firebaseapp.com',
    storageBucket: 'the-mob-state.firebasestorage.app',
    measurementId: 'G-9Z210V708B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXjRbRe0g1mpyGcXaFHT-291dI7TfAZao',
    appId: '1:572351438540:android:com.mobstate.mafia_game_client',
    messagingSenderId: '572351438540',
    projectId: 'the-mob-state',
    storageBucket: 'the-mob-state.firebasestorage.app',
  );
}
